artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: https://github.com/iamdoublea/Text-Summarizer/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


s